###    NOTIFICACIONES    ###
NOTIF_SALIR = -1
NOTIF_ERROR = -1
NOTIF_EXITO = 0

NOTIF_CONEXION_OK = 1
NOTIF_CONEXION_ERROR = 2
NOTIF_CONEXION_TEST = 3

NOTIF_USUARIO_CONECTADO = 4
NOTIF_USUARIO_DESCONECTADO = 5
NOTIF_MENSAJE = 6
NOTIF_REGISTRO = 7
NOTIF_ERROR_REGISTRO = 8
NOTIF_USUARIO_ERROR = 9
NOTIF_CONTACTO = 10

NOTIF_ACTUALIZACION = 50
NOTIF_ACTUALIZACION_EXITO = 51
NOTIF_ACTUALIZACION_ERROR = 52

### SERVIDOR ###
CONEXION_MAX = 50

###   PAQUETES RECIBIDOS  ###
PAQ_CONEXION = 1
PAQ_MENSAJE = 2
PAQ_REGISTRO = 3
PAQ_TEST = 99
PAQ_CONTACTO = 10
PAQ_BUSQUEDA = 707
PAQ_ACTUALIZACION = 555

### REFERENCIAS ###
REF_INICIO_SESION = 11
REF_CONTACTO = 12
REF_REGISTRO = 13
